SETTINGS_KEYS = [
    "WATCHED",
    "SOCKET_PORT",
    "SOCKET_HOST",
    "EXCLUDES",
    "FILE_TYPES",
    "SIGNIFICANCE_THRESHOLD",
    "INDEXING_PROCESSES",
    "BUFFER_PATH",
]
QUERY_STRING_LENGTH = 1024
